# Site settings
title: All About Wood
email: dawidbduplessis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wood /kitchens /cupboards /bathrooms /bars /cabinets /décor
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.allaboutwood.co.za" # the base hostname & protocol for your site
# url: "http://localhost:4000" # the base hostname & protocol for your sitee:  dotto-art
# Build settings
markdown: kramdown
highlighter: none